static_routes:
          static/__pywb: pywb/static/
          static/m: ./static/


collections:
    replay:
        index_paths:
            - http://timetravel.mementoweb.org/api/json/
            - http://timetravel.mementoweb.org/timemap/json/

        server_cls: !!python/name:timetravel.mementoquery.MementoIndexServer

        wb_handler_class: !!python/name:timetravel.mementohandler.MementoHandler
        rewrite_opts:
            punycode_only_links: true
            client:
                skip_postmessage: true

        cookie_scope: removeall
        #fallback: live

    #live:
    #    index_paths: $liveweb
    #    cookie_scope: root

    api:
        index_paths: $liveweb
        wb_handler_class: !!python/name:timetravel.mementohandler.APIHandler


memento_xml: 'http://labs.mementoweb.org/aggregator_config/archivelist.xml'

redir_to_exact: false

framed_replay: inverse

enable_cdx_api: true

enable_memento: true

urlrewriter_class: !!python/name:timetravel.mementohandler.ReUrlRewriter
