static_routes:
          static/default: pywb/static/
          static/m: ./static/


collections:
    replay:
        index_paths:
            - http://timetravel.mementoweb.org/api/json/
            - http://timetravel.mementoweb.org/timemap/json/

        server_cls: !!python/name:timetravel.mementoquery.MementoIndexServer

        wb_handler_class: !!python/name:timetravel.mementohandler.MementoHandler

        #fallback: live

    live:
        index_paths: $liveweb
        cookie_scope: root

    api:
        index_paths: $liveweb
        wb_handler_class: !!python/name:timetravel.mementohandler.APIHandler


query_html: ./templates/query.html

banner_html: ./templates/banner.html

error_html: ./templates/error.html

redirect_to_exact: false

framed_replay: true

enable_http_proxy: true

enable_cdx_api: true

enable_memento: true

